config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "projects#index"

  resources :projects, only: %i[index show]
  resources :tag_projects, only: :index
  resources :prefecture_projects, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id                     :bigint           not null, primary key
#  title                  :string(255)      not null
#  description            :string(255)      not null
#  start_date             :datetime         not null
#  end_date               :datetime         not null
#
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged finders]

  acts_as_taggable_on :tags, :prefectures

  validates :title, :description, :start_date, :end_date, presence: true

  validate :start_and_end_date

  self.per_page = 5

  scope :by_end_date, -> { order("end_date ASC") }

  private
    def start_and_end_date
      return if end_date.blank? || start_date.blank?

      if end_date < start_date
        errors.add(:end_date, I18n.t("cannot_be_before_the_start_date"))
      end
    end

    def should_generate_new_friendly_id?
      slug.blank? || super
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/prefecture_projects_controller.rb
# frozen_string_literal: true

class PrefectureProjectsController < ApplicationController
  before_action :tags
  before_action :prefectures

  def index
    @prefecture = params[:prefecture]
    if @prefecture
      @projects = Project.tagged_with(@prefecture)
                      .all
                      .paginate(page: params[:page])
                      .by_end_date
    else
      redirect_to root_path
    end
  end

  private
    def tags
      @tags = ActsAsTaggableOn::Tagging
                  .includes(:tag)
                  .where(context: "tags")
                  .map { |tagging| { "id" => tagging.tag_id.to_s, "name" => tagging.tag.name } }
                  .uniq
    end

    def prefectures
      @prefectures = ActsAsTaggableOn::Tagging
                         .includes(:tag)
                         .where(context: "prefectures")
                         .map { |tagging| { "id" => tagging.tag_id.to_s, "name" => tagging.tag.name } }
                         .uniq
    end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :tags, except: :show
  before_action :prefectures, except: :show

  def index
    @projects = Project.all.paginate(page: params[:page]).by_end_date
  end

  def show
    @project = Project.friendly.find(params[:id])
    @projects = Project.tagged_with(@project.prefecture_list, any: true).by_end_date
    @related_projects = @projects.reject { |project| project == @project }.first(2)
  end

  private
    def tags
      @tags = ActsAsTaggableOn::Tagging
                  .includes(:tag)
                  .where(context: "tags")
                  .map { |tagging| { "id" => tagging.tag_id.to_s, "name" => tagging.tag.name } }
                  .uniq
    end

    def prefectures
      @prefectures = ActsAsTaggableOn::Tagging
                         .includes(:tag)
                         .where(context: "prefectures")
                         .map { |tagging| { "id" => tagging.tag_id.to_s, "name" => tagging.tag.name } }
                         .uniq
    end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
end

app/controllers/tag_projects_controller.rb
# frozen_string_literal: true

class TagProjectsController < ApplicationController
  before_action :tags
  before_action :prefectures

  def index
    @tag = params[:tag]
    if @tag
      @projects = Project.tagged_with(@tag)
                      .all
                      .paginate(page: params[:page])
                      .by_end_date
    else
      redirect_to root_path
    end
  end

  private
    def tags
      @tags = ActsAsTaggableOn::Tagging
                  .includes(:tag)
                  .where(context: "tags")
                  .map { |tagging| { "id" => tagging.tag_id.to_s, "name" => tagging.tag.name } }
                  .uniq
    end

    def prefectures
      @prefectures = ActsAsTaggableOn::Tagging
                         .includes(:tag)
                         .where(context: "prefectures")
                         .map { |tagging| { "id" => tagging.tag_id.to_s, "name" => tagging.tag.name } }
                         .uniq
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/will_paginate_helper.rb
# frozen_string_literal: true

# rubocop:disable Rails/HelperInstanceVariable

module WillPaginateHelper
  def pagination_links(collection, options = {})
    options[:renderer] ||= LinkRenderer
    options[:class] ||= "pagination"
    options[:inner_window] ||= 1
    options[:outer_window] ||= 0
    options[:container] ||= false
    will_paginate(collection, options)
  end

  class LinkRenderer < WillPaginate::ActionView::LinkRenderer
    protected
      def page_number(page)
        unless page == current_page
          link(page, page, rel: rel_value(page), class: "page-link custom-link-a")
        else
          link(page, "#", class: "page-link custom-link-a custom-link-active")
        end
      end

      def gap
        text = @template.will_paginate_translate(:page_gap) { "&hellip;" }
        %(<li class="disabled page-item custom-link-li"><a>#{text}</a></li>)
      end

      def next_page
        num = @collection.current_page < @collection.total_pages && @collection.current_page + 1
        previous_or_next_page(num, @options[:next_label], "next")
      end

      def previous_or_next_page(page, text, classname)
        if page
          link(text, page, class: classname)
        else
          link(text, "#", class: classname + " disabled")
        end
      end

      def html_container(html)
        tag(:div, tag(:ul, html), container_attributes)
      end

    private
      def link(text, target, attributes = {})
        if target.is_a? Fixnum
          attributes[:rel] = rel_value(target)
          target = url(target)
        end

        unless target == "#"
          attributes[:href] = target
        end

        classname = "page-item custom-link-li"
        attributes.delete(:classname)
        tag(:li, tag(:a, text, attributes), class: classname)
      end
  end
end

app/views/layouts/_footer.html.erb
<div class="footer-basic">
  <footer class="footer">
    <div class="container row offset-1 col-10">
      <div class="col-12 p-0 footer-logo">
        <%= image_tag "footer-logo.png" %>
      </div>
      <div class="row col-12 mt-4">
        <div class="col-md-9 p-0">
          <ul class="row m-0">
            <li class="item footer-item"><%= link_to "運営会社", "#" %></li>
            <li class="item footer-item"><%= link_to "利用規約", "#" %></li>
            <li class="item footer-item"><%= link_to "プライバシーポリシー", "#" %></li>
            <li class="item footer-item"><%= link_to "ヘルプ", "#" %></li>
            <li class="item footer-item"><%= link_to "お問い合わせ", "#" %></li>
          </ul>
        </div>
        <div class="col-md-3 p-0 copyright m-0">
          <span>©2020 Relatedly</span>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light navbar-expand-md">
  <div class="container-fluid">
    <a class="navbar-left" href="<%= root_path %>">
      <%= image_tag "logo.png" %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navcol-1" aria-controls="navcol-1" aria-expanded="false" aria-label="Toggle navigation"  onclick="toggleMobileIcon()">
      <span class="navbar-toggler-icon-mobile" id="navbar-toggler-icon-mobile"></span>
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navcol-1">
      <ul class="nav navbar-nav">
        <li class="nav-item mr-4">
          <%= link_to "運営会社", "#", class: "nav-link nav-operating-company" %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ", "#", class: "nav-link nav-contact-us" %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="below-nav"></div>
<script>
  function toggleMobileIcon() {
    elementClassList = document.getElementsByClassName("navbar-toggler-icon-mobile")[0].classList;
    (elementClassList.length > 1) ? elementClassList.remove("display-inline-block"): elementClassList.add("display-inline-block");
  }
</script>

app/views/layouts/_sidebar.html.erb
<div class="col-md-12 pr-0">
  <div class="tags">
    <span class="color-primary tag"><%= I18n.t("tags") %></span>
    <ul>
      <% @tags.each do |tag| %>
        <li>
          <%= link_to tag["name"], tag_projects_path(tag: tag["name"]), class: "tag-link" %>
        </li>
      <% end %>
    </ul>
  </div>
  <hr>
  <div class="prefectures">
    <span class="color-primary tag"><%= I18n.t("prefectures") %></span>
    <div class="mt-2">
      <div class="row">
        <% @prefectures.each do |prefecture| %>
          <div class="col-xs">
            <%= link_to prefecture["name"], prefecture_projects_path(prefecture: prefecture["name"]), class: "area-link area-span" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OriaiRelatedly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag "/assets/jquery/jquery.min.js", extname: false %>
    <%= javascript_include_tag "/assets/bootstrap/bootstrap.min", extname: false %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/prefecture_projects/index.html.erb
<section class="cards-div">
  <div class="col-md-9 row m-0 m-auto p-0">
    <div class="col-md-8 mb-4">
      <span>
        <%= image_tag "prefecture.png", class: "featured-icon" %>
        <span class="mic-text"><%= @prefecture %></span>
      </span>
      <div class="line"></div>
      <% @projects.each do |project| %>
        <%= render partial: "projects/project", locals: { project: project } %>
        <div class="project-saprator"> </div>
      <% end %>
      <div class="pagination-div col-md-12 mt-5">
        <nav class="col-md-6 m-auto">
          <ul class="pagination">
            <%= pagination_links(@projects) %>
          </ul>
        </nav>
      </div>
    </div>
    <div class="col-md-4 pr-2 pl-2 mb-4">
      <%= render "layouts/sidebar" %>
    </div>
  </div>
</section>

app/views/projects/_project.html.erb
<div class="card p-0 col-md-12">
  <div class="card-body col-md-12">
    <%= link_to project_path(project.slug) do %>
      <%= image_tag "card-img.png", class: "col-md-12 card-image" %>
      <div class="row col-md-12 p-0 m-0">
        <h6 class="text-muted featured-date deadline-date">
          募集終了 | <%= project.end_date.strftime("%Y/%m/%d") %>
        </h6>
      </div>
      <h4 class="card-title"> <%= project.title %></h4>
    <% end %>
    <div>
      <%= link_to project.tag_list.first, tag_projects_path(tag: project.tag_list.first), class: "btn btn-outline-primary featured-btn" %>
      <%= link_to project.prefecture_list.first, prefecture_projects_path(prefecture: project.prefecture_list.first), class: "btn btn-outline-primary featured-btn" %>
    </div>
    <p class="card-text project-description  short-description "><%= strip_tags(project.description).truncate(150) %></p>
  </div>
</div>

app/views/projects/_related_projects.html.erb
<h3 class="related-projects pt-22">同じ地域のプロジェクト</h3>
<div class="mt-3 row">
  <% @related_projects.each do |project| %>
    <div class="col-md-6 mb-4">
      <%= link_to project_path(project.slug) do %>
        <%= image_tag "Rectangle 10.png", class: "col-md-12 p-0" %>
        <span class="project-sub-image-title">
          <span class="start-date release-date">公開日 | <%= project.start_date.strftime("%Y/%m/%d") %></span>
          <span class="end-date  deadline-date">募集終了 | <%= project.end_date.strftime("%Y/%m/%d") %></span>
        </span>
        <h4 class="project-title">
          <strong> <%= project.title %> </strong>
        </h4>
      <% end %>
      <%= link_to project.tag_list.first, tag_projects_path(tag: project.tag_list.first), class: "btn btn-outline-primary featured-btn" %>
      <%= link_to project.prefecture_list.first, prefecture_projects_path(prefecture: project.prefecture_list.first), class: "btn btn-outline-primary featured-btn" %>
      <p class="project-description short-description related-discription">
        <%= strip_tags(project.description).truncate(150) %>
      </p>
    </div>
  <% end %>
</div>

app/views/projects/index.html.erb
<section class="main">
  <span class="main-text">地域と私達のつながりをつくる</span>
</section>
<section class="cards-div">
  <div class="col-md-12 row m-0 p-0">
    <div class="col-md-7 p-0">
      <span>
        <%= image_tag "Framemic.png", class: "featured-icon" %>
        <span class="mic-text">注目のプロジェクト</span>
      </span>
      <div class="line"></div>
      <% @projects.each do |project| %>
        <%= render partial: "project", locals: { project: project } %>
        <div class="project-separator"> </div>
      <% end %>
    </div>
    <div class="col-md-5">
      <%= render "layouts/sidebar" %>
    </div>
  </div>
</section>

app/views/projects/show.html.erb
<section class="col-md-9 main-section">
  <span class="breadcrumb m-0 p-0 mt-2">TOP > プロジェクトを探す >
    <%= @project.title %>
  </span>
  <div class="mt-2">
    <div class="row">
      <div class="col-sm-5 col-md-5">
        <%= link_to @project.tag_list.first, tag_projects_path(tag: @project.tag_list.first), class: "btn btn-outline-primary featured-btn" %>
        <%= link_to @project.prefecture_list.first, prefecture_projects_path(prefecture: @project.prefecture_list.first), class: "btn btn-outline-primary featured-btn" %>
      </div>
      <div class="col-sm-7 col-md-7">
        <div class="top-date-muted">
          公開日 : <%= @project.start_date.strftime("%Y/%m/%d") %>　終了日 ： <%= @project.end_date.strftime("%Y/%m/%d") %>
        </div>
      </div>
    </div>
    <h4 class="project-detail-heading">
      <%= @project.title %>
    </h4>
  </div>
  <div class="mt-4 button-padding-buttom">
    <button class="btn btn-primary circular-btn primary-color float-right" type="button" style="margin-bottom: 2%;">
      <i class="fa fa-paper-plane-o" aria-hidden="true"></i> 応募する
    </button>
  </div>
  <br>
  <div class="mt-4">
    <%= image_tag "thumbnail.png", class: "col-md-12 p-0" %>
  </div>
  <div class="mt-4 project-description">
    <%= sanitize @project.description %>
  </div>
  <hr class="divider-line">
  <div class="mt-4 text-center">
    <button class="btn btn-primary btn-rectangle primary-color btn-round-apply " type="button">
      <i class="fa fa-paper-plane-o" aria-hidden="true"></i> 応募する
    </button>
  </div>
  <div class="mt-5 related-project-container">
    <%= render partial: "related_projects" %>
  </div>
</section>

app/views/tag_projects/index.html.erb
<section class="cards-div">
  <div class="col-md-12 row m-0 p-0">
    <div class="col-md-8 p-0">
      <span>
        <%= image_tag "tag.png", class: "featured-icon op-6" %>
        <span class="mic-text"><%= @tag %></span>
      </span>
      <div class="line"></div>
      <% @projects.each do |project| %>
        <%= render partial: "projects/project", locals: { project: project } %>
        <div class="project-saprator"> </div>
      <% end %>
      <div class="pagination-div col-md-12 mt-5">
        <nav class="col-md-6 m-auto">
          <ul class="pagination">
            <%= pagination_links(@projects) %>
          </ul>
        </nav>
      </div>
    </div>
    <div class="col-md-4">
      <%= render "layouts/sidebar" %>
    </div>
  </div>
</section>